"""The physical safe state and the fault timeline, judged on the plant truth of one trajectory.

A safe state is not a gate command.  Six-switch-off, an active short circuit or "PWM off" are bridge configurations;
whether the machine is in a safe state is decided by what it physically does.  The prohibited torque-generation
conditions (each judged on the samples of the trajectory, after an origin and a declared transition allowance):

    C1  torque generated by converting energy FROM the HV system: |T_em| > T_tol while the bridge takes power from
        the DC link (P_dc = v_dc i_dc > P_tol);
    C2  torque generated by converting energy TO the HV system: |T_em| > T_tol while the bridge feeds the DC link
        (P_dc < -P_tol) - the uncontrolled rectification of six-switch-off above the back-EMF onset;
    C3  torque generated by actively pulsing the output stage: |T_em| > T_tol while the bridge is commanded to PWM
        (the pulsing steps of a soft transition included);
    C4  any other torque that violates a declared torque limit: the shaft torque outside [T_min, T_max] (signed: the
        braking torque of an active short circuit is a negative torque at positive speed).

T_em is the electromagnetic (air-gap) torque the machine generates; C4 compares the shaft torque (air gap minus the
rotational loss: the torque the machine delivers to the transmission).  The tolerances T_tol, P_tol, the limits of C4,
the transition allowance and the hold time are declared inputs: an undeclared C4 limit makes C4 UNKNOWN (never a
PASS), and the verdict says so.

The fault timeline keeps six instants apart (one clock, the fault onset is never reset by a late detection):

    t_fault          the first primary fault (latent faults wait for a demand and are not the onset);
    t_criterion      the first sample at which the detecting mechanism's criterion was violated (before its
                     debounce / glitch filter): the deviation start as the monitor saw it;
    t_detect         the qualified detection (the mechanism's trip) - the reaction request is issued here;
    t_gate_applied   the first bridge command of the reaction in effect at the gates (after the path delay);
    t_terminal       the first static safe configuration (ASC / six-switch-off / sequential ASC) after it - later than
                     t_gate_applied when the reaction starts with pulsing steps;
    t_physical_safe  the first instant from which C1..C4 hold for the hold time.
"""

from __future__ import annotations

import math

import numpy as np

PASS, FAIL, UNKNOWN, NA = "PASS", "FAIL", "UNKNOWN", "NOT_APPLICABLE"
LATENT_KINDS = ("mechanism_disabled", "path_lost", "contactor_stuck", "redundant_supply_lost")
PWM_CODE = 0                          # engine.BRIDGE_CODES["pwm"]
TEST_CODE = 7                         # engine.BRIDGE_CODES["test"] (a self-test pulse pattern)
STATIC_CODES = (1, 2, 3, 5, 6)        # asc_low, asc_high, six_switch_off, seq_asc_low, seq_asc_high
CONDITIONS = ("C1", "C2", "C3", "C4")
TEXT = {"C1": "torque from energy taken from the HV system",
        "C2": "torque from energy fed to the HV system",
        "C3": "torque from active pulsing of the output stage",
        "C4": "torque outside the declared torque limit"}


def _arr(tr, k):
    return np.asarray(tr[k], dtype=float)


def _get(obj, key):
    return obj[key] if isinstance(obj, dict) else getattr(obj, key)


def _runs(t: np.ndarray, m: np.ndarray) -> list:
    """Intervals [t_a, t_b] where the boolean sample mask holds (a sample holds until the next sample)."""
    out = []
    i, n = 0, len(t)
    while i < n:
        if m[i]:
            j = i
            while j + 1 < n and m[j + 1]:
                j += 1
            out.append((float(t[i]), float(t[min(j + 1, n - 1)])))
            i = j + 1
        else:
            i += 1
    return out


def condition_masks(tr: dict, torque_tol_Nm: float, power_tol_W: float, t_min_Nm: float | None,
                    t_max_Nm: float | None) -> dict:
    """Per-sample violation masks of C1..C4 (C4 None when no limit is declared)."""
    T_em, T_sh = _arr(tr, "T_em"), _arr(tr, "T_shaft")
    P = _arr(tr, "v_dc") * np.nan_to_num(_arr(tr, "i_dc"), nan=0.0)
    br = _arr(tr, "bridge")
    gen = np.abs(T_em) > torque_tol_Nm
    out = {"C1": gen & (P > power_tol_W), "C2": gen & (P < -power_tol_W),
           "C3": gen & ((br == PWM_CODE) | (br == TEST_CODE))}
    if t_min_Nm is None and t_max_Nm is None:
        out["C4"] = None
    else:
        lo = -math.inf if t_min_Nm is None else float(t_min_Nm)
        hi = math.inf if t_max_Nm is None else float(t_max_Nm)
        out["C4"] = (T_sh < lo) | (T_sh > hi)
    return out


def judge_safe_state(result, origin_s: float | None, *, torque_tol_Nm: float, power_tol_W: float,
                     t_min_Nm: float | None = None, t_max_Nm: float | None = None, transition_s: float = 0.0,
                     hold_s: float = 0.0, deadline_s: float | None = None, deadline_open: str | None = None,
                     conditions=CONDITIONS, until_s: float | None = None) -> dict:
    """Is the customer-style safe state reached after ``origin_s`` (+ the transition allowance) and held?

    ``deadline_s``: the time from the origin within which it must be reached (``deadline_open``: the name of an
    OPEN parameter instead - the time is measured, the verdict is UNKNOWN).  Returns the per-condition evidence,
    ``t_safe`` (absolute), ``reached_after_s`` (from the origin) and the verdict with its reasons."""
    tr = _get(result, "trace")
    status = _get(result, "status")
    t = _arr(tr, "t")
    if origin_s is None:
        return {"verdict": NA, "reasons": ["no origin: no fault / detection to start from"], "conditions": {},
                "t_safe": None, "reached_after_s": None}
    a = float(origin_s) + float(transition_s)
    end = float(t[-1]) if len(t) else 0.0
    if until_s is not None:
        end = min(end, float(until_s))              # the safe state is required only until then
    masks = condition_masks(tr, torque_tol_Nm, power_tol_W, t_min_Nm, t_max_Nm)
    win = (t >= a - 1e-15) & (t <= end + 1e-15)
    reasons, cond = [], {}
    viol_any = np.zeros(len(t), dtype=bool)
    unknown_c4 = False
    T_em, P = _arr(tr, "T_em"), _arr(tr, "v_dc") * np.nan_to_num(_arr(tr, "i_dc"), nan=0.0)
    for c in conditions:
        m = masks.get(c)
        if m is None:
            unknown_c4 = True
            cond[c] = {"verdict": UNKNOWN, "text": TEXT[c], "reason": "no torque limit declared (TLSR limit OPEN)"}
            continue
        mw = m & win
        runs = _runs(t, mw)
        dur = sum(b - x for x, b in runs)
        viol_any |= mw
        k = np.where(mw)[0]
        cond[c] = {"text": TEXT[c], "violated": bool(len(k)), "first_s": float(t[k[0]]) if len(k) else None,
                   "last_s": runs[-1][1] if runs else None, "duration_s": dur,
                   "peak_torque_Nm": float(np.max(np.abs(T_em[k]))) if len(k) else 0.0,
                   "peak_power_W": float(np.max(np.abs(P[k]))) if len(k) else 0.0}
    # the earliest instant after which no judged condition is violated any more
    k = np.where(viol_any)[0]
    if len(k) == 0:
        t_safe = a
    else:
        last = k[-1]
        t_safe = float(t[last + 1]) if last + 1 < len(t) and t[last + 1] <= end + 1e-15 else None
    held = None if t_safe is None else end - t_safe
    if t_safe is None:
        verdict = FAIL
        reasons.append("a prohibited torque condition persists to the end of the trajectory: the safe state is not "
                       "reached")
    elif held < hold_s - 1e-12:
        verdict = UNKNOWN
        reasons.append(f"the simulation left the model at {end * 1e3:.4g} ms before the hold time elapsed"
                       if status != "completed" else
                       f"held only {held * 1e3:.4g} ms of the required {hold_s * 1e3:g} ms before the horizon")
    else:
        verdict = PASS
    for c in conditions:
        info = cond[c]
        if "violated" not in info:
            continue
        if not info["violated"]:
            info["verdict"] = PASS                  # never violated after the origin (and its allowance)
        elif info["last_s"] is not None and info["last_s"] >= end - 1e-9:
            info["verdict"] = FAIL                  # still violated at the end of the trajectory
        else:
            info["verdict"] = PASS if end - info["last_s"] >= hold_s - 1e-12 else UNKNOWN
    reached = None if t_safe is None else t_safe - float(origin_s)
    if verdict == PASS and deadline_s is not None and reached is not None and reached > deadline_s + 1e-12:
        verdict = FAIL
        reasons.append(f"reached {reached * 1e3:.4g} ms after the origin > the deadline {deadline_s * 1e3:g} ms")
    if verdict == PASS and deadline_s is None and deadline_open:
        verdict = UNKNOWN
        reasons.append(f"reached {reached * 1e3:.4g} ms after the origin; the deadline {deadline_open} is OPEN")
    if verdict == PASS and unknown_c4:
        verdict = UNKNOWN
        reasons.append("C1-C3 hold; C4 cannot be judged without a declared torque limit")
    if status != "completed" and verdict == PASS:
        reasons.append(f"the run left the model at {end * 1e3:.4g} ms after the hold was shown")
    return {"verdict": verdict, "reasons": reasons, "conditions": cond, "t_safe": t_safe, "reached_after_s": reached,
            "origin_s": float(origin_s), "window_from_s": a, "hold_s": hold_s,
            "params": {"torque_tol_Nm": torque_tol_Nm, "power_tol_W": power_tol_W, "t_min_Nm": t_min_Nm,
                       "t_max_Nm": t_max_Nm, "transition_s": transition_s}}


def fault_timeline(result, mechanisms=None, torque_tol_Nm: float = 5.0, power_tol_W: float = 500.0,
                   t_min_Nm: float | None = None, t_max_Nm: float | None = None, hold_s: float = 0.0) -> dict:
    """The six instants of one trajectory (absolute times, s; None when the instant does not occur).  ``mechanisms``
    restricts the detection to these mechanism ids (e.g. the ones allocated to a requirement)."""
    events = _get(result, "events")
    summary = _get(result, "summary")
    setup = _get(result, "setup_echo")
    faults = [f for f in setup.get("faults", []) if f["kind"] not in LATENT_KINDS]
    t_fault = min((f["t_s"] for f in faults), default=None)
    t0 = t_fault if t_fault is not None else 0.0
    allowed = set(mechanisms) if mechanisms else None
    det = next((e for e in events if e["kind"] == "detection" and e["t"] >= t0 - 1e-12
                and (allowed is None or e["source"] in allowed)), None)
    t_detect = det["t"] if det else None
    # the reaction request: the first detection whose reaction was executed or the first request of a safe state
    # (a scenario's command, a supervisor reason), whichever comes first; a detection without a reaction (a report,
    # a battery-management action) requests nothing - it stays the request only when nothing else is found
    acted = {e["source"] for e in events if e["kind"] == "actuation"}
    cands = [e for e in events if e["t"] >= t0 - 1e-12 and (
        (e["kind"] == "detection" and e["source"] in acted and (allowed is None or e["source"] in allowed))
        or e["kind"] == "safe_state_request")]
    req = min(cands, key=lambda e: e["t"]) if cands else det
    t_req = req["t"] if req else None
    t_crit = None
    if det is not None:
        crit = [c for c in summary.get("criteria", []) if c["mech"] == det["source"] and c["t"] <= det["t"] + 1e-12
                and c["t"] >= t0 - 1e-12]
        t_crit = crit[-1]["t"] if crit else det["t"]
    act = next((e for e in events if e["kind"] == "actuation" and t_req is not None and e["t"] >= t_req - 1e-12),
               None)
    t_gate = t_term = None
    if act is not None:
        br = [e for e in events if e["kind"] == "bridge" and e["t"] >= act["t"] - 1e-12]
        first = next((e for e in br if e.get("command") != "pwm"), None)
        t_gate = first["t"] if first else act["t"]
        tr = _get(result, "trace")
        tt, codes = _arr(tr, "t"), _arr(tr, "bridge")
        k = np.where((tt >= t_gate - 1e-15) & np.isin(codes, STATIC_CODES))[0]
        t_term = float(tt[k[0]]) if len(k) else None
        if act.get("reaction") == "torque_zero":
            t_gate = act["t"]
    if t_fault is not None:                 # one clock: an instant found within the 1e-12 s tolerance of the onset
        t_crit, t_detect, t_req, t_gate, t_term = (   # (the same step, accumulated time) is the onset, never before it
            None if x is None else max(x, t_fault) for x in (t_crit, t_detect, t_req, t_gate, t_term))
    phys = judge_safe_state(result, t_gate if t_gate is not None else t_req, torque_tol_Nm=torque_tol_Nm,
                            power_tol_W=power_tol_W, t_min_Nm=t_min_Nm, t_max_Nm=t_max_Nm, hold_s=hold_s)
    return {"t_fault": t_fault, "t_criterion": t_crit, "t_detect": t_detect,
            "t_reaction_req": t_req, "t_gate_applied": t_gate, "t_terminal": t_term,
            "t_physical_safe": phys.get("t_safe"), "detected_by": det["source"] if det else (
                req["source"] if req else None),
            "reaction": act.get("reaction") if act else None, "safe_state": phys}


def excess_impulse(result, t_from: float, t_to: float, limit_Nm: float, side: str = "high") -> float:
    """The torque impulse beyond a limit over [t_from, t_to] (N*m*s): high side integrates T - limit where positive,
    low side limit - T where positive (signed torque, never |T|)."""
    tr = _get(result, "trace")
    t, T = _arr(tr, "t"), _arr(tr, "T_shaft")
    m = (t >= t_from - 1e-15) & (t <= t_to + 1e-15)
    if m.sum() < 2:
        return 0.0
    ex = np.maximum(0.0, T[m] - limit_Nm) if side == "high" else np.maximum(0.0, limit_Nm - T[m])
    tt = t[m]
    return float(np.sum(0.5 * (ex[1:] + ex[:-1]) * np.diff(tt)))


def time_to_window_hold(result, t_from: float, half_width_Nm: float, center_Nm: float = 0.0,
                        hold_s: float = 0.0) -> float | None:
    """From ``t_from``, the time at which the shaft torque enters [center +- half_width] and stays there to the end
    (and at least ``hold_s``); None if it never does within the trajectory."""
    tr = _get(result, "trace")
    t, T = _arr(tr, "t"), _arr(tr, "T_shaft")
    out = (np.abs(T - center_Nm) > half_width_Nm) & (t >= t_from - 1e-15)
    k = np.where(out)[0]
    t_in = float(t_from) if len(k) == 0 else (float(t[k[-1] + 1]) if k[-1] + 1 < len(t) else None)
    if t_in is None or float(t[-1]) - t_in < hold_s - 1e-12:
        return None
    return t_in - float(t_from)
